version: "3.7"
services:
  client:
    # stdin_open: true
    # tty: true
    build:
      context: ./client
      dockerfile: Dockerfile.prod
      args:
        - REACT_APP_SERVER_URL=value
    ports:
      - "3000:3000"
      - "2000:80"
    volumes:
      - ./client/src:/app/src
    environment:
      - REACT_APP_SERVER_URL=http://localhost:8800
  
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    ports:
      - "8800:8800"
    volumes:
      - ./server/src:/app/src
    environment:
      - PORT=8800
      - MONGO_URL=mongodb://mongo:27017/crm-project
    depends_on:
      - mongo
    
  mongo:
    image: mongo
    volumes:
      - ./mongo/data:/data/db
    ports:
      - '27017:27017'